apiVersion: v1
kind: Service
metadata:
  name: trend-app-service
  labels:
    app: trend-app-service
spec:
  type: LoadBalancer
  selector:
    app: trend-app-service
  ports:
    - protocol: TCP 
      port: 80
      targetPort: 3000
